sudo: required
services:
  - docker

before_install:
  # Build docker image
  - docker build -t rubensa/aws-cli --label "maintainer=Ruben Suarez <rubensa@gmail.com>"

script:
  # Check aws cli version
  - docker run rubensa/aws-cli aws --version

after_success:
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Put images on Docker Hub
  - docker push rubensa/aws-cli

